<<<<<<< Updated upstream
-- MySQL Script generated by MySQL Workbench
-- Thu Mar  5 19:37:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurante` DEFAULT CHARACTER SET utf8 ;
USE `restaurante` ;

-- -----------------------------------------------------
-- Table `restaurante`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Mesa` (
  `idmesa` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `numero_personas` INT NOT NULL,
  PRIMARY KEY (`idmesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Recepcionista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Recepcionista` (
  `idrecepcionista` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrecepcionista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Reserva` (
  `idreserva` INT NOT NULL AUTO_INCREMENT,
  `hora` TIME NOT NULL,
  `fecha` DATE NOT NULL,
  `Cliente_idcliente` INT NOT NULL,
  `Mesa_idmesa` INT NOT NULL,
  `Recepcionista_idrecepcionista` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_Reserva_Cliente1_idx` (`Cliente_idcliente` ASC) ,
  INDEX `fk_Reserva_Mesa1_idx` (`Mesa_idmesa` ASC) ,
  INDEX `fk_Reserva_Recepcionista1_idx` (`Recepcionista_idrecepcionista` ASC) ,
  CONSTRAINT `fk_Reserva_Cliente1`
    FOREIGN KEY (`Cliente_idcliente`)
    REFERENCES `restaurante`.`Cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Mesa1`
    FOREIGN KEY (`Mesa_idmesa`)
    REFERENCES `restaurante`.`Mesa` (`idmesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Recepcionista1`
    FOREIGN KEY (`Recepcionista_idrecepcionista`)
    REFERENCES `restaurante`.`Recepcionista` (`idrecepcionista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `Reserva_idreserva` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_Pedido_Reserva1_idx` (`Reserva_idreserva` ASC) ,
  CONSTRAINT `fk_Pedido_Reserva1`
    FOREIGN KEY (`Reserva_idreserva`)
    REFERENCES `restaurante`.`Reserva` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Chef`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Chef` (
  `idchef` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `tarjetaprofesional` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idchef`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Plato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Plato` (
  `idplato` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `Chef_idchef` INT NOT NULL,
  `Categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idplato`),
  INDEX `fk_Plato_Chef1_idx` (`Chef_idchef` ASC) ,
  INDEX `fk_Plato_Categoria1_idx` (`Categoria_idcategoria` ASC) ,
  CONSTRAINT `fk_Plato_Chef1`
    FOREIGN KEY (`Chef_idchef`)
    REFERENCES `restaurante`.`Chef` (`idchef`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plato_Categoria1`
    FOREIGN KEY (`Categoria_idcategoria`)
    REFERENCES `restaurante`.`Categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Ingrediente` (
  `idingrediente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idingrediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Factura` (
  `idfactura` INT UNSIGNED NOT NULL,
  `montoFinal` DOUBLE NOT NULL,
  `Pedido_idpedido` INT NOT NULL,
  PRIMARY KEY (`idfactura`),
  INDEX `fk_Factura_Pedido1_idx` (`Pedido_idpedido` ASC) ,
  CONSTRAINT `fk_Factura_Pedido1`
    FOREIGN KEY (`Pedido_idpedido`)
    REFERENCES `restaurante`.`Pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Administrador` (
  `idadministrador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`administrador1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`administrador1` (
  `idadministrador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`paciente` (
  `idpaciente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  PRIMARY KEY (`idpaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`especialidad` (
  `idespecialidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idespecialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`medico` (
  `idmedico` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `tarjetaprofesional` VARCHAR(45) NOT NULL,
  `especialidad_idespecialidad` INT NOT NULL,
  PRIMARY KEY (`idmedico`),
  INDEX `fk_medico_especialidad_idx` (`especialidad_idespecialidad` ASC) ,
  CONSTRAINT `fk_medico_especialidad`
    FOREIGN KEY (`especialidad_idespecialidad`)
    REFERENCES `restaurante`.`especialidad` (`idespecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`consultorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`consultorio` (
  `idconsultorio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idconsultorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`cita` (
  `idcita` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `medico_idmedico` INT NOT NULL,
  `paciente_idpaciente` INT NOT NULL,
  `consultorio_idconsultorio` INT NOT NULL,
  PRIMARY KEY (`idcita`),
  INDEX `fk_cita_medico1_idx` (`medico_idmedico` ASC) ,
  INDEX `fk_cita_paciente1_idx` (`paciente_idpaciente` ASC) ,
  INDEX `fk_cita_consultorio1_idx` (`consultorio_idconsultorio` ASC) ,
  CONSTRAINT `fk_cita_medico1`
    FOREIGN KEY (`medico_idmedico`)
    REFERENCES `restaurante`.`medico` (`idmedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cita_paciente1`
    FOREIGN KEY (`paciente_idpaciente`)
    REFERENCES `restaurante`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cita_consultorio1`
    FOREIGN KEY (`consultorio_idconsultorio`)
    REFERENCES `restaurante`.`consultorio` (`idconsultorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Pedido_Plato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Pedido_Plato` (
  `Pedido_idpedido` INT NOT NULL,
  `Plato_idplato` INT NOT NULL,
  PRIMARY KEY (`Pedido_idpedido`, `Plato_idplato`),
  INDEX `fk_Pedido_has_Plato_Plato1_idx` (`Plato_idplato` ASC) ,
  INDEX `fk_Pedido_has_Plato_Pedido1_idx` (`Pedido_idpedido` ASC) ,
  CONSTRAINT `fk_Pedido_has_Plato_Pedido1`
    FOREIGN KEY (`Pedido_idpedido`)
    REFERENCES `restaurante`.`Pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Plato_Plato1`
    FOREIGN KEY (`Plato_idplato`)
    REFERENCES `restaurante`.`Plato` (`idplato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Plato_Ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Plato_Ingrediente` (
  `Plato_idplato` INT NOT NULL,
  `Ingrediente_idingrediente` INT NOT NULL,
  PRIMARY KEY (`Plato_idplato`, `Ingrediente_idingrediente`),
  INDEX `fk_Plato_has_Ingrediente_Ingrediente1_idx` (`Ingrediente_idingrediente` ASC) ,
  INDEX `fk_Plato_has_Ingrediente_Plato1_idx` (`Plato_idplato` ASC) ,
  CONSTRAINT `fk_Plato_has_Ingrediente_Plato1`
    FOREIGN KEY (`Plato_idplato`)
    REFERENCES `restaurante`.`Plato` (`idplato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plato_has_Ingrediente_Ingrediente1`
    FOREIGN KEY (`Ingrediente_idingrediente`)
    REFERENCES `restaurante`.`Ingrediente` (`idingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
=======
-- MySQL Script generated by MySQL Workbench
-- Sun Mar  8 16:41:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurante` DEFAULT CHARACTER SET utf8 ;
USE `restaurante` ;

-- -----------------------------------------------------
-- Table `restaurante`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Mesa` (
  `idmesa` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `numero_personas` INT NOT NULL,
  PRIMARY KEY (`idmesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Recepcionista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Recepcionista` (
  `idrecepcionista` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrecepcionista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Reserva` (
  `idreserva` INT NOT NULL AUTO_INCREMENT,
  `hora` TIME NOT NULL,
  `fecha` DATE NOT NULL,
  `Cliente_idcliente` INT NOT NULL,
  `Mesa_idmesa` INT NOT NULL,
  `Recepcionista_idrecepcionista` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_Reserva_Cliente1_idx` (`Cliente_idcliente` ASC) ,
  INDEX `fk_Reserva_Mesa1_idx` (`Mesa_idmesa` ASC) ,
  INDEX `fk_Reserva_Recepcionista1_idx` (`Recepcionista_idrecepcionista` ASC) ,
  CONSTRAINT `fk_Reserva_Cliente1`
    FOREIGN KEY (`Cliente_idcliente`)
    REFERENCES `restaurante`.`Cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Mesa1`
    FOREIGN KEY (`Mesa_idmesa`)
    REFERENCES `restaurante`.`Mesa` (`idmesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Recepcionista1`
    FOREIGN KEY (`Recepcionista_idrecepcionista`)
    REFERENCES `restaurante`.`Recepcionista` (`idrecepcionista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `Reserva_idreserva` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_Pedido_Reserva1_idx` (`Reserva_idreserva` ASC) ,
  CONSTRAINT `fk_Pedido_Reserva1`
    FOREIGN KEY (`Reserva_idreserva`)
    REFERENCES `restaurante`.`Reserva` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Chef`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Chef` (
  `idchef` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `tarjetaprofesional` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idchef`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Plato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Plato` (
  `idplato` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `Chef_idchef` INT NOT NULL,
  `Categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idplato`),
  INDEX `fk_Plato_Chef1_idx` (`Chef_idchef` ASC) ,
  INDEX `fk_Plato_Categoria1_idx` (`Categoria_idcategoria` ASC) ,
  CONSTRAINT `fk_Plato_Chef1`
    FOREIGN KEY (`Chef_idchef`)
    REFERENCES `restaurante`.`Chef` (`idchef`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plato_Categoria1`
    FOREIGN KEY (`Categoria_idcategoria`)
    REFERENCES `restaurante`.`Categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Ingrediente` (
  `idingrediente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idingrediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Factura` (
  `idfactura` INT UNSIGNED NOT NULL,
  `montoFinal` DOUBLE NOT NULL,
  `Pedido_idpedido` INT NOT NULL,
  PRIMARY KEY (`idfactura`),
  INDEX `fk_Factura_Pedido1_idx` (`Pedido_idpedido` ASC) ,
  CONSTRAINT `fk_Factura_Pedido1`
    FOREIGN KEY (`Pedido_idpedido`)
    REFERENCES `restaurante`.`Pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Administrador` (
  `idadministrador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadministrador`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `restaurante`.`Pedido_Plato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Pedido_Plato` (
  `Pedido_idpedido` INT NOT NULL,
  `Plato_idplato` INT NOT NULL,
  PRIMARY KEY (`Pedido_idpedido`, `Plato_idplato`),
  INDEX `fk_Pedido_has_Plato_Plato1_idx` (`Plato_idplato` ASC) ,
  INDEX `fk_Pedido_has_Plato_Pedido1_idx` (`Pedido_idpedido` ASC) ,
  CONSTRAINT `fk_Pedido_has_Plato_Pedido1`
    FOREIGN KEY (`Pedido_idpedido`)
    REFERENCES `restaurante`.`Pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Plato_Plato1`
    FOREIGN KEY (`Plato_idplato`)
    REFERENCES `restaurante`.`Plato` (`idplato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`Plato_Ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante`.`Plato_Ingrediente` (
  `Plato_idplato` INT NOT NULL,
  `Ingrediente_idingrediente` INT NOT NULL,
  PRIMARY KEY (`Plato_idplato`, `Ingrediente_idingrediente`),
  INDEX `fk_Plato_has_Ingrediente_Ingrediente1_idx` (`Ingrediente_idingrediente` ASC) ,
  INDEX `fk_Plato_has_Ingrediente_Plato1_idx` (`Plato_idplato` ASC) ,
  CONSTRAINT `fk_Plato_has_Ingrediente_Plato1`
    FOREIGN KEY (`Plato_idplato`)
    REFERENCES `restaurante`.`Plato` (`idplato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plato_has_Ingrediente_Ingrediente1`
    FOREIGN KEY (`Ingrediente_idingrediente`)
    REFERENCES `restaurante`.`Ingrediente` (`idingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
>>>>>>> Stashed changes
